name: Build and Deploy

on:
  push:
    branches:
      - main # Change this to your main branch

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0 # You can change this to your required Ruby version

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }}.git gh-pages
          cp -a _site/. gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update Jekyll site"
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          new_branch: gh-pages
