name: Build and Deploy

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
         ruby-version: '3.3' # Not needed with a .ruby-version file
         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }}.git gh-pages
          cp -a _site/. gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update Jekyll site"
          git push origin gh-pages

    env:
      JEKYLL_ENV: production
